
##list

#access_token : 'olar'
GET http://localhost:8080/api/public/v1/products/
#95801617-d67b-46a7-90d2-1d1f32a0cc95
access_token : 08HEsaiY-T16dNwqQ1SXJnUlzOFUNZ9rlNKVOjlqiI3XzKB5boJGeV372zBmbpVyvc1EB-J6GhyIhHGDCnVh0DrD3PBnjgxo2ZnJmJPEcmmAzU62WsEAv78Sf2q5YnU0s2EGCaZAZlWZvO2FOnUYREVDF0nz1BH0AvQRrmj_j6uwK8eCD0kI4d87_JZF1ZAZ48zTNKjkMMqzA3JfjPHP9ZwZbZZuKaZ0CxJlPjtfolVFiyXyEiBOQaF7IMueR1XS9qJJCEvO5KObunD0oyUvxoD0KpbnLDdxmloZuRz1KVnJJcxjXDYFxbCn8lPAZlmQXaf1RVa5D9VAx-gJ2ucTvk97JxOZxZgnhh87cPH8xyO2JEZmASMTACM_3FSgPWBw5rwbO89uhT_aZJkWtkleiqa5cZsGnY6HmPbT79QelHgmU0-1IkM0GgNMn7gFd1vWhkA--soef4sRGnqIEOnLVn7MHwEpe9Dd

#GET http://localhost:8080/products/909f8d1e-14af-435e-b2b1-2ee99add91e6
## post

# POST http://localhost:8080/api/public/v2/token
# Content-Type: application/json

# {
#   "ClientId": "b521b6b2-b9b4-4a30-881d-3b63dece0006",
#   "ClientSecret": "08Qkje79NwWRx5BdgNJsIkBuITt5cIVO",
#   "ClientId:ClientSecret": "b521b6b2-b9b4-4a30-881d-3b63dece0006:08Qkje79NwWRx5BdgNJsIkBuITt5cIVO",
#   "Base64": "YjUyMWI2YjItYjliNC00YTMwLTg4MWQtM2I2M2RlY2UwMDA2OjA4UWtqZTc5TndXUng1QmRnTkpzSWtCdUlUdDVjSVZP"
# }

#95801617-d67b-46a7-90d2-1d1f32a0cc95

# POST http://localhost:8080/api/public/v1/products/
# Content-Type: application/json
# access_token : 08HEsaiY-T16dNwqQ1SXJnUlzOFUNZ9rlNKVOjlqiI3XzKB5boJGeV372zBmbpVyvc1EB-J6GhyIhHGDCnVh0DrD3PBnjgxo2ZnJmJPEcmmAzU62WsEAv78Sf2q5YnU0s2EGCaZAZlWZvO2FOnUYREVDF0nz1BH0AvQRrmj_j6uwK8eCD0kI4d87_JZF1ZAZ48zTNKjkMMqzA3JfjPHP9ZwZbZZuKaZ0CxJlPjtfolVFiyXyEiBOQaF7IMueR1XS9qJJCEvO5KObunD0oyUvxoD0KpbnLDdxmloZuRz1KVnJJcxjXDYFxbCn8lPAZlmQXaf1RVa5D9VAx-gJ2ucTvk97JxOZxZgnhh87cPH8xyO2JEZmASMTACM_3FSgPWBw5rwbO89uhT_aZJkWtkleiqa5cZsGnY6HmPbT79QelHgmU0-1IkM0GgNMn7gFd1vWhkA--soef4sRGnqIEOnLVn7MHwEpe9Dd

# {
#   "OrderNumber": "789123",  
#   "type": "Digital",
#   "name": "Pedido",
#   "description": "teste description 3",
#   "price": 1000000,
#   "weight": 2000000,
#   "expirationDate": "2025-04-21 10:32:00",
#   "maxNumberOfInstallments": 1,
#   "quantity": 1,
#   "sku": "teste 3",
#   "shipping": {
#     "type": "WithoutShipping",
#     "name": "teste3",
#     "price": 1000000000
#   },
#   "recurrent": {
#     "interval": "Monthly",
#     "endDate": "2025-05-23"
#   },
#   "softDescriptor": "Pedido1234"
# }