
##list

#access_token : 'olar'
#GET http://localhost:3000/products

#GET http://localhost:3000/products/909f8d1e-14af-435e-b2b1-2ee99add91e6
## post

POST http://localhost:3000/token
Content-Type: application/json

{
  "ClientId": "b521b6b2-b9b4-4a30-881d-3b63dece0006",
  "ClientSecret": "08Qkje79NwWRx5BdgNJsIkBuITt5cIVO",
  "ClientId:ClientSecret": "b521b6b2-b9b4-4a30-881d-3b63dece0006:08Qkje79NwWRx5BdgNJsIkBuITt5cIVO",
  "Base64": "YjUyMWI2YjItYjliNC00YTMwLTg4MWQtM2I2M2RlY2UwMDA2OjA4UWtqZTc5TndXUng1QmRnTkpzSWtCdUlUdDVjSVZP"
}



# POST http://localhost:3000/products
# Content-Type: application/json
# access_token : olar

# {
#   "OrderNumber": "123456",  
#   "type": "Digital",
#   "name": "Pedido",
#   "description": "teste description",
#   "price": 1000000,
#   "weight": 2000000,
#   "expirationDate": "2027-06-19 16:30:00",
#   "maxNumberOfInstallments": 1,
#   "quantity": 2,
#   "sku": "teste",
#   "shipping": {
#     "type": "WithoutShipping",
#     "name": "teste",
#     "price": 1000000000
#   },
#   "recurrent": {
#     "interval": "Monthly",
#     "endDate": "2024-02-23"
#   },
#   "softDescriptor": "Pedido1234"
# }